### ISSUE TITLE
Grid example fails to compile

### ISSUE THREAD

**Issue by uartie** [01org/libyami-utils#21]
The `--enable-dmabuf` configure option enables the `grid` example to be compiled.  However, if also configured with `--enable-avformat`, the grid example fails to compile.

```
In file included from ../tests/decodeinputavformat.cpp:20:0:
../tests/decodeinputavformat.h:22:34: fatal error: libavformat/avformat.h: No such file or directory
compilation terminated.
Makefile:710: recipe for target '../tests/grid-decodeinputavformat.o' failed
make[3]: *** [../tests/grid-decodeinputavformat.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from ../tests/decodeinput.cpp:28:0:
../tests/decodeinputavformat.h:22:34: fatal error: libavformat/avformat.h: No such file or directory
compilation terminated.
Makefile:696: recipe for target '../tests/grid-decodeinput.o' failed
make[3]: *** [../tests/grid-decodeinput.o] Error 1
```

The problem is that the makefile does not add `LIBAVFORMAT` flags to the `grid` compile target.

**Comment by chivakker** [comment]
This configure works with grid

./autogen.sh --enable-dmabuf --enable-debug --enable-avformat --enable-x11 --enable-v4l2 --enable-md5

What's your full configure line?

**Comment by uartie** [comment]
`--enable-debug --enable-dmabuf --enable-x11 --enable-avformat`
