### ISSUE TITLE
Is libavformat dependent on ffmpeg's libavcodec & libavformat

### ISSUE THREAD

**Issue by laxigithub** [01org/libyami-utils#25]
when configured libyami-utils with --enable-libavformat, the build is failing with dependent libraries: libavcodec and libavformat from ffmpeg. Can you please confirm configuring libavformat meaning yami uses ffmpeg version of it.

**Comment by chivakker** [comment]
On Thu, Sep 1, 2016 at 10:34 AM, Laxman <notifications@github.com> wrote:

> when configured libyami-utils with --enable-libavformat, the build is
> failing with dependent libraries: libavcodec and libavformat from ffmpeg.
> Can you please confirm configuring libavformat meaning yami uses ffmpeg
> version of it.
>

libyami-utils does use ffmpeg avformat to demux container formats and other
bitstreeam packetized contents.  It will work with different versions of
ffmpeg, if you find that a particular doesn't work, let us know.

**Comment by xuguangxin** [comment]
Hi @laxigithub 
You can refer to https://github.com/01org/libyami/wiki/Build for build things. Search entire page for avformat or ffmpeg may help you.
