### ISSUE TITLE
How to encode surfaces created from prime fd ?

### ISSUE THREAD

**Issue by zhijianli88** [01org/libyami-utils#51]
Hi guy,

I try to encode a surface created from prime fd(backed by drm_i915_gem_vgtbuffer).
But it seems to got an incorrect output by my code. It always display a green screen where i expect a
guest desktop snapshot.
Can you please give me some suggestions?

Here is part of my code:
1.  create a VASurfaceID from prime fd {
   VASurfaceAttribExternalBuffers external;  
   memset(&external, 0, sizeof(external));
   
   external.pixel_format = VA_FOURCC_BGRX;
   external.width = m_width;
   external.height = m_height;
   external.data_size = m_width \* m_height \* BPP / 8;
   external.num_planes = 1;
   external.pitches[0] = m_width; //can be obtained from vcreate FIXME
   external.buffers = prime_fd; /\* import from vgtbuffer*/
   external.num_buffers = 1;
   
   VASurfaceAttrib attribs[2];
   attribs[0].flags = VA_SURFACE_ATTRIB_SETTABLE;
   attribs[0].type = VASurfaceAttribMemoryType;
   attribs[0].value.type = VAGenericValueTypeInteger;
   attribs[0].value.value.i = VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME;
   
   attribs[1].flags = VA_SURFACE_ATTRIB_SETTABLE;
   attribs[1].type = VASurfaceAttribExternalBufferDescriptor;
   attribs[1].value.type = VAGenericValueTypePointer;
   attribs[1].value.value.p = &external;
   
   VAStatus vaStatus = vaCreateSurfaces(*(m_display.get()), VA_RT_FORMAT_RGB32, m_width, m_height, &surfaces,  1,attribs, sizeof(attribs)/sizeof(attribs[0]));
   
   if (vaStatus != VA_STATUS_SUCCESS){
       fprintf(stderr,"VA SURFACE CREATE FAILED!\n");
       return -1;
   }
   return 0;
   }
2.  create a h264 encoder {
   encoder = createVideoEncoder(YAMI_MIME_H264);
   ...
   encoder->start()
   }
3. doing encode {
   VideoFrame frame;
   frame.surface = surface; /\* create by step 1 */
   frame.fourcc = YAMI_FOURCC_RGBX;
   encoder->encode(frame);
   }
4. get the coded buffer {
   output = EncodeOutput::create(outputfile,videoWidth,videoHeight,codec);
   do{
   status = encoder->getOutput(&outputBuffer,false);
   if(status == ENCODE_SUCCESS
      && output->write(outputBuffer.data,outputBuffer.dataSize)){
       printf("output data size:%d\n",outputBuffer.dataSize);
   }
   }while(status != ENCODE_BUFFER_NO_MORE);
   }

**Comment by xuguangxin** [comment]
I do not know why you can create VASurface, but you may need change `external.buffers = prime_fd` to `external.buffers = &prime_fd`, because va treat buffers as array:
```
    if (external_memory_type == I965_SURFACE_MEM_GEM_FLINK)
        obj_surface->bo = drm_intel_bo_gem_create_from_name(i965->intel.bufmgr,
                                                            "gem flinked vaapi surface",
                                                            memory_attibute->buffers[index]);
    else if (external_memory_type == I965_SURFACE_MEM_DRM_PRIME)
        obj_surface->bo = drm_intel_bo_gem_create_from_prime(i965->intel.bufmgr,
                                                             memory_attibute->buffers[index],
                                                             obj_surface->size);

```

**Comment by xuguangxin** [comment]
other think maybe the pitch, pitch usually express as byte not pixel

**Comment by zhijianli88** [comment]
> I do not know why you can create VASurface, but you may need change external.buffers = prime_fd to external.buffers = &prime_fd, because va treat buffers as array:

you are right, it should be &prime_fd.  I had fixed it and I have created VASurface successfully.
Today, i dumped the 3)VideoFrame to a jpeg file, i can see a rough guest desktop what i expect.

i'm quite new for libyami,  so i'm not clear how to set the pitch.

**Comment by zhijianli88** [comment]
more question: Do I need to convert the VideoFrame from RGBX to YUV before I do the encoding `encoder->encode(frame);`

**Comment by xuguangxin** [comment]
you can check this  https://www.x.org/wiki/Development/Documentation/HowVideoCardsWork/ and this http://stackoverflow.com/questions/20541111/how-to-calculate-framebuffer-pitch

**Comment by xuguangxin** [comment]
No need, We will crate new surface and convert it in libva. However if you have nv12 surface pool you many have better performance. PooledFrameAllocator may make your life easier:

```
template <class T>
class VideoPool : public EnableSharedFromThis<VideoPool<T> >
{
public:

    SharedPtr<T> alloc()
    {
        SharedPtr<T> ret;
        boost::upgrade_lock<boost::shared_mutex> lock(m_mutex);

        if (!m_freed.empty()) {
            T* p = m_freed.front();
            m_freed.pop_front();
            ret.reset(p, Recycler(this->shared_from_this()));
        }
        return ret;
    }

    VideoPool(std::deque<SharedPtr<T> >& buffers)
    {
            m_holder.swap(buffers);
            for (size_t i = 0; i < m_holder.size(); i++) {
                m_freed.push_back(m_holder[i].get());
            }
    }

private:
    void recycle(T* ptr)
    {
        boost::upgrade_lock<boost::shared_mutex> lock(m_mutex);
        m_freed.push_back(ptr);
    }

    class Recycler
    {
    public:
        Recycler(const SharedPtr<VideoPool<T> >& pool)
            :m_pool(pool)
        {
        }
        void operator()(T* ptr) const
        {
            m_pool->recycle(ptr);
        }
    private:
        SharedPtr<VideoPool<T> > m_pool;
    };

    boost::shared_mutex m_mutex;

    std::deque<T*> m_freed;
    std::deque<SharedPtr<T> > m_holder;
};

struct SurfaceDestoryer
{
private:
    SharedPtr<VADisplay> m_display;
    std::vector<VASurfaceID> m_surfaces;
public:
    SurfaceDestoryer(const SharedPtr<VADisplay>& display, std::vector<VASurfaceID>& surfaces)
        :m_display(display)
    {
        m_surfaces.swap(surfaces);
    }
    void operator()(VideoPool<VideoFrame>* pool)
    {
        if (m_surfaces.size())
            vaDestroySurfaces(*m_display, &m_surfaces[0], m_surfaces.size());
        delete pool;
    }

};

class PooledFrameAllocator
{
public:
    PooledFrameAllocator(const SharedPtr<VADisplay>& display, int poolsize)
        :m_display(display)
        , m_poolsize(poolsize)
    {
    }
    bool setFormat(uint32_t fourcc, int width, int height)
    {
        std::vector<VASurfaceID> surfaces;
        surfaces.resize(m_poolsize);

        VASurfaceAttrib attrib;
        attrib.flags = VA_SURFACE_ATTRIB_SETTABLE;
        attrib.type = VASurfaceAttribPixelFormat;
        attrib.value.type = VAGenericValueTypeInteger;
        attrib.value.value.i = fourcc;


        VAStatus status = vaCreateSurfaces(*m_display, VA_RT_FORMAT_YUV420, width, height,
                                           &surfaces[0], surfaces.size(),
                                           &attrib, 1);
        if (status != VA_STATUS_SUCCESS) {
            ELOG_ERROR("create surface failed, %s", vaErrorStr(status));
            return false;
        }
        std::deque<SharedPtr<VideoFrame> > buffers;
        for (size_t i = 0;  i < surfaces.size(); i++) {
            SharedPtr<VideoFrame> f(new VideoFrame);
            memset(f.get(), 0, sizeof(VideoFrame));
            f->surface = (intptr_t)surfaces[i];
            f->fourcc = fourcc;
            buffers.push_back(f);
        }
        m_pool.reset(new VideoPool<VideoFrame>(buffers), SurfaceDestoryer(m_display, surfaces));
        return true;
    }

    SharedPtr<VideoFrame> alloc()
    {
        return  m_pool->alloc();
    }
private:
    SharedPtr<VADisplay> m_display;
    SharedPtr<VideoPool<VideoFrame> > m_pool;
    int m_poolsize;
};

```

**Comment by zhijianli88** [comment]
> you can check this https://www.x.org/wiki/Development/Documentation/HowVideoCardsWork/ and this http://stackoverflow.com/questions/20541111/how-to-calculate-framebuffer-pitch

Thank you very much, I will have look.

**Comment by zhijianli88** [comment]
> No need, we will create new surface and convert the RGB to NV12 in libva. However if you have NV12 surface pool you many have better performance. PooledFrameAllocator may make your life easier:

My demo have implemented a suface pool [primefd-demo:https://github.com/zhijianli88/primefd-demo]( https://github.com/zhijianli88/primefd-demo) 
But I have not bring it up. It need more investigation.

**Comment by zhijianli88** [comment]
Thanks, I will have a look;
