### ISSUE TITLE
Setup travis-ci

### ISSUE THREAD

**Issue by seanvk** [01org/libyami-utils#74]
for basic build checks on pull requests

**Comment by xuguangxin** [comment]
Hi @seanvk , seems you are busy with other tasks, would mind let @yizhouwei help on this and coverity setup? https://github.com/01org/intel-vaapi-driver/blob/master/.travis.yml   is good reference for him.

**Comment by seanvk** [comment]
@xuguangxin That is fine.

**Comment by xuguangxin** [comment]
this fixed by #85. thanks for report
